language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t cl/react-fs-test-app -f ./frontend/Dockerfile.dev ./frontend

script: 
  - docker run -e CI=true cl/react-fs-test-app npm run test

after_success:
  # 이미지 생성
  - docker build -t chaelynjang/docker-frontend ./frontend
  - docker build -t chaelynjang/docker-backend ./backend
  - docker build -t chaelynjang/docker-nginx   ./nginx

  # Docker Hub 로그인
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  
  # Docker Hub에 push
  - docker push chaelynjang/docker-frontend
  - docker push chaelynjang/docker-backend
  - docker push chaelynjang/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Docker-fullstack-app-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-548976652634
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY