language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t cl/react-fs-test-app -f ./frontend/Dockerfile.dev ./frontend

script: 
  - docker run -e CI=true cl/react-fs-test-app npm run test

after_success:
  # 이미지 생성
  - docker build -t cl/docker-frontend ./frontend
  - docker build -t cl/docker-backend ./backend
  - docker build -t cl/docker-nginx   ./nginx

  # Docker Hub 로그인
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  
  # Docker Hub에 push
  - docker push cl/docker-frontend
  - docker push cl/docker-backend
  - docker push cl/docker-nginx